export class CommonConstants {
  // 满屏宽度
  public static readonly FULL_SCREEN_WIDTH = '100%'
  // 满屏高度
  public static readonly FULL_SCREEN_HEIGHT = '100%'
  // 组件默认大小
  public static readonly DEFAULT_SIZE = 40
  // 小组件尺寸
  public static readonly SMALL_SIZE = 24
  // 大组件尺寸
  public static readonly LARGE_SIZE = 64
  // 动画迭代次数（无限循环）
  public static readonly ANIMATION_ITERATIONS = -1
  // 旋转0角度
  public static readonly ROTATE_0 = 0
  // 旋转45角度
  public static readonly ROTATE_45 = 45
  // 旋转-45角度
  public static readonly NEGATIVE_ROTATE_45 = -45
  // 旋转90角度
  public static readonly ROTATE_90 = 90
  // 旋转180角度
  public static readonly ROTATE_180 = 180
  // 旋转-180角度
  public static readonly NEGATIVE_ROTATE_180 = -180
  // 旋转轴向量坐标（默认值1）
  public static readonly ROTATE_AXIS_1 = 1
  // 旋转轴向量坐标（默认值0）
  public static readonly ROTATE_AXIS_0 = 0
}
