/**
 * 延时常量类
 */
export class DelayConstant {
  /**
   * 延时0毫秒
   */
  public static readonly DELAY_0: number = 0;
  /**
   * 提前时间-100毫秒
   */
  public static readonly DELAY_NEG_100: number = -100;
  /**
   * 提前时间-200毫秒
   */
  public static readonly DELAY_NEG_200: number = -200;
  /**
   * 提前时间-300毫秒
   */
  public static readonly DELAY_NEG_300: number = -300;
  /**
   * 提前时间-400毫秒
   */
  public static readonly DELAY_NEG_400: number = -400;
  /**
   * 提前时间-500毫秒
   */
  public static readonly DELAY_NEG_500: number = -500;
  /**
   * 提前时间-600毫秒
   */
  public static readonly DELAY_NEG_600: number = -600;
  /**
   * 提前时间-700毫秒
   */
  public static readonly DELAY_NEG_700: number = -700;
  /**
   * 提前时间-800毫秒
   */
  public static readonly DELAY_NEG_800: number = -800;
  /**
   * 提前时间-900毫秒
   */
  public static readonly DELAY_NEG_900: number = -900;
  /**
   * 提前时间-1000毫秒
   */
  public static readonly DELAY_NEG_1000: number = -1000;
  /**
   * 提前时间-1100毫秒
   */
  public static readonly DELAY_NEG_1100: number = -1100;
  /**
   * 提前时间-1200毫秒
   */
  public static readonly DELAY_NEG_1200: number = -1200;
  /**
   * 提前时间-1300毫秒
   */
  public static readonly DELAY_NEG_1300: number = -1300;
  /**
   * 提前时间-1400毫秒
   */
  public static readonly DELAY_NEG_1400: number = -1400;
  /**
   * 提前时间-1500毫秒
   */
  public static readonly DELAY_NEG_1500: number = -1500;
  /**
   * 提前时间-1600毫秒
   */
  public static readonly DELAY_NEG_1600: number = -1600;
  /**
   * 提前时间-1700毫秒
   */
  public static readonly DELAY_NEG_1700: number = -1700;
  /**
   * 提前时间-1800毫秒
   */
  public static readonly DELAY_NEG_1800: number = -1800;
  /**
   * 提前时间-1900毫秒
   */
  public static readonly DELAY_NEG_1900: number = -1900;
  /**
   * 提前时间-2000毫秒
   */
  public static readonly DELAY_NEG_2000: number = -2000;

  /**
   * 延迟时间100毫秒
   */
  public static readonly DELAY_100: number = 100;
  /**
   * 延迟时间160毫秒
   */
  public static readonly DELAY_160: number = 160;
  /**
   * 延迟时间200毫秒
   */
  public static readonly DELAY_200: number = 200;
  /**
   * 延迟时间300毫秒
   */
  public static readonly DELAY_300: number = 300;
  /**
   * 延迟时间400毫秒
   */
  public static readonly DELAY_400: number = 400;
  /**
   * 延迟时间500毫秒
   */
  public static readonly DELAY_500: number = 500;
  /**
   * 延迟时间600毫秒
   */
  public static readonly DELAY_600: number = 600;
  /**
   * 延迟时间700毫秒
   */
  public static readonly DELAY_700: number = 700;
  /**
   * 延迟时间800毫秒
   */
  public static readonly DELAY_800: number = 800;
  /**
   * 延迟时间900毫秒
   */
  public static readonly DELAY_900: number = 900;
  /**
   * 延迟时间1000毫秒
   */
  public static readonly DELAY_1000: number = 1000;
  /**
   * 延迟时间1100毫秒
   */
  public static readonly DELAY_1100: number = 1100;
  /**
   * 延迟时间1200毫秒
   */
  public static readonly DELAY_1200: number = 1200;
  /**
   * 延迟时间1300毫秒
   */
  public static readonly DELAY_1300: number = 1300;
  /**
   * 延迟时间1400毫秒
   */
  public static readonly DELAY_1400: number = 1400;
  /**
   * 延迟时间1500毫秒
   */
  public static readonly DELAY_1500: number = 1500;
  /**
   * 延迟时间1600毫秒
   */
  public static readonly DELAY_1600: number = 1600;
  /**
   * 延迟时间1700毫秒
   */
  public static readonly DELAY_1700: number = 1700;
  /**
   * 延迟时间1800毫秒
   */
  public static readonly DELAY_1800: number = 1800;
  /**
   * 延迟时间1900毫秒
   */
  public static readonly DELAY_1900: number = 1900;
  /**
   * 延迟时间2000毫秒
   */
  public static readonly DELAY_2000: number = 2000;
}
