/**
 * duration常量类
 */
export class DurationConstant {
  /**
   * 动画时长0毫秒
   */
  public static readonly DURATION_0: number = 0;
  /**
   * 动画时长100毫秒
   */
  public static readonly DURATION_100: number = 100;
  /**
   * 动画时长200毫秒
   */
  public static readonly DURATION_200: number = 200;
  /**
   * 动画时长300毫秒
   */
  public static readonly DURATION_300: number = 300;
  /**
   * 动画时长400毫秒
   */
  public static readonly DURATION_400: number = 400;
  /**
   * 动画时长450毫秒
   */
  public static readonly DURATION_450: number = 450;
  /**
   * 动画时长500毫秒
   */
  public static readonly DURATION_500: number = 500;
  /**
   * 动画时长600毫秒
   */
  public static readonly DURATION_600: number = 600;
  /**
   * 动画时长700毫秒
   */
  public static readonly DURATION_700: number = 700;
  /**
   * 动画时长800毫秒
   */
  public static readonly DURATION_800: number = 800;
  /**
   * 动画时长900毫秒
   */
  public static readonly DURATION_900: number = 900;
  /**
   * 动画时长1000毫秒
   */
  public static readonly DURATION_1000: number = 1000;
  /**
   * 动画时长1100毫秒
   */
  public static readonly DURATION_1100: number = 1100;
  /**
   * 动画时长1200毫秒
   */
  public static readonly DURATION_1200: number = 1200;
  /**
   * 动画时长1300毫秒
   */
  public static readonly DURATION_1300: number = 1300;
  /**
   * 动画时长1400毫秒
   */
  public static readonly DURATION_1400: number = 1400;
  /**
   * 动画时长1500毫秒
   */
  public static readonly DURATION_1500: number = 1500;
  /**
   * 动画时长1600毫秒
   */
  public static readonly DURATION_1600: number = 1600;
  /**
   * 动画时长1700毫秒
   */
  public static readonly DURATION_1700: number = 1700;
  /**
   * 动画时长1800毫秒
   */
  public static readonly DURATION_1800: number = 1800;
  /**
   * 动画时长1900毫秒
   */
  public static readonly DURATION_1900: number = 1900;
  /**
   * 动画时长2000毫秒
   */
  public static readonly DURATION_2000: number = 2000;
}
