/**
 * 透明度常量
 */
export class OpacityConstants {
  /** 完全透明 */
  public static readonly HIDDEN = 0
  /** 五分之一不透明 */
  public static readonly ONE_FIFTH_OPAQUE = 0.2
  /** 五分之二不透明 */
  public static readonly TWO_FIFTHS_OPAQUE = 0.4
  /** 半透明 */
  public static readonly HALF_TRANSPARENT = 0.5
  /** 五分之三不透明 */
  public static readonly THREE_FIFTHS_OPAQUE = 0.6
  /** 五分之四不透明 */
  public static readonly FOUR_FIFTHS_OPAQUE = 0.8
  /** 完全不透明 */
  public static readonly VISIBLE = 1
}
