/**
 * MIT License
 *
 * Copyright (C) 2025 Huawei Device Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { Style } from "library"

export const COLORS: number[] = [
  0XFFD55400,
  0XFF2B3E51,
  0XFF00BD9C,
  0XFF227FBB,
  0XFF7F8C8D,
  0XFFFFCC5C,
  0XFFD55400,
  0XFF1AAF5D,
]

export const SPIN_KIT_STYLE: Style[] = [
  Style.ROTATING_PLANE,
  Style.DOUBLE_BOUNCE,
  Style.WAVE,
  Style.WANDERING_CUBES,
  Style.PULSE,
  Style.CHASING_DOTS,
  Style.THREE_BOUNCE,
  Style.CIRCLE,
  Style.CUBE_GRID,
  Style.FADING_CIRCLE,
  Style.FOLDING_CUBE,
  Style.ROTATING_CIRCLE,
  Style.MULTIPLE_PULSE,
  Style.PULSE_RING,
  Style.MULTIPLE_PULSE_RING,
]

export const SPIN_KIT_NAME: string[] = [
  "rotating_plane",
  "double_bounce",
  "wave",
  "wandering_cubes",
  "pulse",
  "chasing_dots",
  "three_bounce",
  "circle",
  "cube_grid",
  "fading_circle",
  "folding_cube",
  "rotating_circle",
  "multiple_pulse",
  "pulse_ring",
  "multiple_pulse_ring",
]

export class Constants{
  public static readonly HALF_SCREEN_WIDTH: string = "50%"
}
