import { Style } from "spinkit"

export const COLORS: number[] = [
  0XFFD55400,
  0XFF2B3E51,
  0XFF00BD9C,
  0XFF227FBB,
  0XFF7F8C8D,
  0XFFFFCC5C,
  0XFFD55400,
  0XFF1AAF5D,
]

export const SPIN_KIT_STYLE: Style[] = [
  Style.ROTATING_PLANE,
  Style.DOUBLE_BOUNCE,
  Style.WAVE,
  Style.WANDERING_CUBES,
  Style.PULSE,
  Style.CHASING_DOTS,
  Style.THREE_BOUNCE,
  Style.CIRCLE,
  Style.CUBE_GRID,
  Style.FADING_CIRCLE,
  Style.FOLDING_CUBE,
  Style.ROTATING_CIRCLE,
  Style.MULTIPLE_PULSE,
  Style.PULSE_RING,
  Style.MULTIPLE_PULSE_RING,
]

export const SPIN_KIT_NAME: string[] = [
  "rotating_plane",
  "double_bounce",
  "wave",
  "wandering_cubes",
  "pulse",
  "chasing_dots",
  "three_bounce",
  "circle",
  "cube_grid",
  "fading_circle",
  "folding_cube",
  "rotating_circle",
  "multiple_pulse",
  "pulse_ring",
  "multiple_pulse_ring",
]

export class Constants{
  public static readonly HALF_SCREEN_WIDTH: string = "50%"
}
